### ISSUE TITLE
Error with some API keys

### ISSUE THREAD

**Issue by SpongyBacon** [ninja-works/buycraft-java#3]
When trying to add a new Buycraft...

````
java.lang.StringIndexOutOfBoundsException: String index out of range: 8
	at java.lang.String.substring(String.java:1951)
	at ninja.smirking.buycraft.serialization.PaymentDeserializer.deserialize(PaymentDeserializer.java:63)
	at ninja.smirking.buycraft.serialization.PaymentDeserializer.deserialize(PaymentDeserializer.java:38)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:875)
	at com.google.gson.Gson.fromJson(Gson.java:848)
	at ninja.smirking.buycraft.Buycraft.lambda$getPayments$2(Buycraft.java:209)
	at ninja.smirking.buycraft.Buycraft$$Lambda$2/1768908071.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at ninja.smirking.buycraft.Buycraft.getPayments(Buycraft.java:209)
	at ninja.smirking.buycraft.Buycraft.getPayments(Buycraft.java:157)
	at com.spongybacon.spongybot.commands.mc.BuycraftNotifier.onCommand(BuycraftNotifier.java:110)
	at com.spongybacon.spongybot.commands.CommandManager.handle(CommandManager.java:132)
	at com.spongybacon.spongybot.MasterListener$1.run(MasterListener.java:68)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745
````

BuycraftNotifier.java:110-112
`            for (BuycraftPayment p : b.getPayments()) {
                payments.add(p);
            }`

BuycraftNotifer.java:
````
package com.spongybacon.spongybot.commands.mc;

import com.codelanx.codelanxlib.util.Scheduler;
import com.samczsun.skype4j.chat.Chat;
import com.samczsun.skype4j.chat.IndividualChat;
import com.samczsun.skype4j.user.User;
import com.spongybacon.spongybot.Main;
import com.spongybacon.spongybot.Msg;
import com.spongybacon.spongybot.commands.Command;
import com.spongybacon.spongybot.commands.CommandGroup;
import ninja.smirking.buycraft.Buycraft;
import ninja.smirking.buycraft.api.BuycraftPayment;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

public class BuycraftNotifier extends Command {

    private HashMap<String, Buycraft> buycrafts;
    private HashMap<String, List<BuycraftPayment>> knownPayments;

    public BuycraftNotifier() {
        super(CommandGroup.MC, User.Role.ADMIN, "#buycraftnotifier", "#buycraft", "#bcn");

        //this.buycraft = new Buycraft(SECRET);
        this.buycrafts = new HashMap<>();
        this.knownPayments = new HashMap<>();

        Scheduler.runAsyncTaskRepeat(new Runnable() {
            @Override
            public void run() {
               System.out.println("Checking buycrafts...");

               for (String s : buycrafts.keySet()) {
                   Buycraft buycraft = buycrafts.get(s);

                   for (BuycraftPayment payment : buycraft.getPayments()) {
                       if (!knownPayments.get(s).contains(payment)) {
                           Msg.send(Main.skype.getChat(s), "<b>New BuyCraft Payment!</b>New payment from " + payment.getUsername() + "!\nPayment UUID: " + payment.getUniqueId() + "\nPackage: " + payment.getPackages().get(0) + "\nPrice: " + payment.getCurrency() + " " + payment.getPrice() + "\nTime: " + payment.getHumanTime());
                           knownPayments.get(s).add(payment);
                       }
                   }
               }

               System.out.println("Checked buycrafts.");
            }
        }, 60, 60);
    }

    @Override
    public void onCommand(User user, Chat chat, String command, String[] args) {
        /*for (BuycraftPackage p : buycraft.getPackages()) {
            System.out.println(p.getName() + " - " + p.getDescription());
        }*/

        //Msg.send(user, chat, "test");

        if (args.length <= 1) {
            //Msg.send(user, chat, "BEFORE YOU USE THIS, MAKE SURE TO USE PRIVATE MESSAGES TO THE BOT FOR ADDING & REMOVING AS YOUR SECRET KEY SHOULD REMAIN A SECRET!");
            //Msg.send(user, chat, "Usage: #bcn add <secret key> <chat identity> - adds a chat for buycraft payment notifications." +
            //         " #bcn remove <secret key> - removes a chat from buycraft notifications.");
            //Msg.send(user, chat, "\nTo find your secret key, go onto https://server.buycraft.net/webstore, login and click 'servers'. Then copy the secret key for the server (multiple server support coming soon" +
            //        "\nTo find the chat identity, type #chatinfo in that chat and copy what it returns.");
            //return;

            //Msg.send(user, chat, "Subcommands: add, remove.");

            Msg.send(user, chat, "Allows you to add notifications for when you get a purchase on buycraft!\n\n<u>ADD/REMOVE IN A PRIVATE CHAT, YOUR SECRET KEY SHOULD REMAIN SECRET!</u>\n\n#bcn add [secret key] [chat identity]\n#bcn remove [secret key]\n\n<b>For the secret key:</b> Visit https://server.buycraft.net/servers, then copy the secret key of the server.\n<b>For the chat identity:</b> Use #chatinfo in the chat you want notifications to be displayed in.");
        }

        if (args[1].equalsIgnoreCase("add")) {
            if (!(chat instanceof IndividualChat)) {
                Msg.send(user, chat, "Do this in a private chat please! (Add the bot)");
                return;
            }

            if (args.length < 4) {
                Msg.send(user, chat, "Usage: #bcn add <private key> <chat identity>");
                return;
            }

            if (buycrafts.containsKey(args[3])) {
                Msg.send(user, chat, "That chat already has a buycraft server assigned to it :(");
                return;
            }

            Chat c = Main.skype.getChat(args[3]);
            if (c == null) {
                Msg.send(user, chat, args[3] + " is not a valid chat :(");
                return;
            }

            if (c.getUser(user.getUsername()).getRole() != User.Role.ADMIN) {
                Msg.send(user, chat, "You must be an admin in that chat to do this!");
                return;
            }

            buycrafts.put(c.getIdentity(), new Buycraft(args[2]));
            Buycraft b = buycrafts.get(c.getIdentity());

            List<BuycraftPayment> payments = new ArrayList<>();
            for (BuycraftPayment p : b.getPayments()) {
                payments.add(p);
            }
            knownPayments.put(c.getIdentity(), payments);

            Msg.send(user, chat, "Added that server for buycraft payment notification!");
            return;
        } else if (args[1].equalsIgnoreCase("remove")) {
            Msg.send(user, chat, "Just wait for the next restart :P Will come soon.");
            return;
        }
    }
}
````

**Comment by SpongyBacon** [comment]
Turns out was not an issue with the API

**Comment by SpongyBacon** [comment]
Happening with some keys.

**Comment by Fireflies** [comment]
Unless Buycraft can retrieve the username of the player then UUIDs will be empty strings.

**Comment by Fireflies** [comment]
Upon further inspection it appears both offline mode and non existent usernames cause this problem.
